backend:
  name: git-gateway
  branch: main
  login: true

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Artikel"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Isi", name: "body", widget: "markdown" }

  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Konten Homepage"
        name: "homepage"
        file: "content/homepage.md"
        fields:
          - { label: "Hero Judul", name: "hero_title", widget: "string" }
          - { label: "Quote", name: "quote", widget: "string" }
          - { label: "Tentang", name: "about", widget: "text" }
